export default {
    MESSAGE_HELLO:                  'MESSAGE_HELLO',
    MESSAGE_WHO_ARE_YOU:            'MESSAGE_WHO_ARE_YOU',
    MESSAGE_CHECK_NICKNAME:         'MESSAGE_CHECK_NICKNAME',
    MESSAGE_REQUEST_NICKNAME:       'MESSAGE_REQUEST_NICKNAME',
    MESSAGE_NAME_IN_USE:            'MESSAGE_NAME_IN_USE',
    MESSAGE_NAME_TOO_SHORT:         'MESSAGE_NAME_TOO_SHORT',
    MESSAGE_NAME_TOO_LONG:          'MESSAGE_NAME_TOO_LONG',
    MESSAGE_NAME_BAD_CHARACTERS:    'MESSAGE_NAME_BAD_CHARACTERS',
    MESSAGE_NICKNAME_VALID:         'MESSAGE_NICKNAME_VALID',
    MESSAGE_NICKNAME_GRANTED:       'MESSAGE_NICKNAME_GRANTED',
    MESSAGE_USER_LIST:              'MESSAGE_USER_LIST',
    MESSAGE_USER_JOINS:             'MESSAGE_USER_JOINS',
    MESSAGE_USER_LEAVES:            'MESSAGE_USER_LEAVES',
    MESSAGE_USER_STATE_CHANGE:      'MESSAGE_USER_STATE_CHANGE',
    MESSAGE_CHAT:                   'MESSAGE_CHAT',
    MESSAGE_SERVER_MESSAGE:         'MESSAGE_SERVER_MESSAGE'
}
